- name: Install libs for Ubuntu
  apt: name={{ item }} state=present
  with_items:
   - dh-php5
   - php-pear
   - php5-apcu
   - php5-cli
   - php5-common
   - php5-curl
   - php5-dev
   - php5-fpm
   - php5-gd
   - php5-gmp
   - php5-imap
   - php5-json
   - php5-mcrypt
   - php5-memcached
   - php5-mysqlnd
   - php5-pgsql
   - php5-readline
   - php5-sqlite
   - php5-xdebug
   - pkg-php-tools
   - ntp
   - openssh-server
   - telnet
   - git
   - iptables-persistent
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: for nginx latest version
  apt_key: url=http://nginx.org/keys/nginx_signing.key
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: add nginx source list
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present


- name: add nginx source list
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: install latest nginx
  apt: name=nginx state=latest
