- name: Install nagios plugins for Ubuntu
  apt: name={{ item }} state=present
  with_items:
   - dh-php5
   - php-pear
   - php5-apcu
   - php5-cli
   - php5-common
   - php5-curl
   - php5-dev
   - php5-fpm
   - php5-gd
   - php5-gmp
   - php5-imap
   - php5-json
   - php5-mcrypt
   - php5-memcached
   - php5-mysqlnd
   - php5-pgsql
   - php5-readline
   - php5-sqlite
   - php5-xdebug
   - pkg-php-tools
   - ntp
   - openssh-server
   - telnet
   - git
   - iptables-persistent
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
